config/routes.rb
HackMe::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"

  get "log_in"  => "sessions#new",     :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new",        :as => "sign_up"

  resources :sessions
  resources :users
  resources :articles

  root :to => "static_pages#home"
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  attr_accessible :title, :description, :user_id

  validates_length_of :title, :minimum => 5
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles

  attr_accessible :name, :email, :password, :homepage, :is_admin

  validates :name, :email, :password, :presence => true
  validates :email, :format =>  { :with => /@.+\./, :message => "E-Mail should contain @ and at least one dot" }

  def to_s
    name
  end

  def admin?
    is_admin
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password == password
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
    if current_user
      @article.user_id=current_user.id

      respond_to do |format|
        if @article.save
          format.html { redirect_to @article, notice: 'Article was successfully created.' }
          format.json { render json: @article, status: :created, location: @article }
        else
          format.html { render action: "new" }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to articles_path, notice: 'Article not created'
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @articles = Article.all
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.is_admin = false

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_unless_blank( text, url )
    if url.blank? then "-- kein Link --" else link_to(text, url) end
  end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<% if current_user then %> 
  <p><%= link_to 'write new article', new_article_path %></p>
<% end %>
<% @articles.each do |article| %>
  <h2><%= article.title %></h2>
  <% if current_user then %> 
    <p>
      <%= link_to 'Edit', edit_article_path(article) %> |
      <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
  <%= raw article.description %>

<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titel:</b>
  <%= @article.title %>
</p>

<p>
  <b>Text des Artikels:</b>
  <%= raw @article.description %>
</p>

<p>
  <b>Autor/in:</b>
  <%= link_to @article.user, user_path(@article.user) %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hack Me!  A Ruby on Rails App.</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="content">
    <nav>
      <ul>
        <li><%= link_to_unless_current "Home", root_path %></li>
        <li><%= link_to_unless_current "Articles", articles_path %></li>
        <li><%= link_to_unless_current "People", users_path %></li>
        <li><%= link_to_unless_current "Help", static_pages_help_path %></li>
        <% if current_user %>
        <li style="float:right">  
          Logged in as <%= current_user.name %>
          <%= link_to_unless_current "Log out", log_out_path %>
        </li>  
        <% else %>
        <li style="float:right">  
          <%= link_to_unless_current "Sign up", sign_up_path %> or
          <%= link_to_unless_current "Log in",  log_in_path  %>
        </li>  
        <% end %>
      </ul>
    </nav>
    <%= yield %>
  </div>

</body>
</html>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>What should you do with this app?</p>

<ul>
<li><a href="#find">Find all the problems</a></li>
<li><a href="#hack">Try and exploit the problems, one by one</a></li>
<li><a href="#fix">Fix the problems, so your hacks won't work any more</a></li>
</ul>



<h2 id="find">Find alle the problems</h2>

<p>This app exhibits several security problems
commonly found in rails apps.  Find them!</p>

<p>Sources:</p>

<ul>
<li><a href="http://guides.rubyonrails.org/security.html">Rails Security Guide</a></li>
<li><a href="https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project">OWASP Top 10</a></li>
</ul>


<h2 id="hack">Try to exploit the problems</h2>

<p>For every weakness you find: try and build a hack to exploit it.</p>
<p>One simple way of doing it might be to build a rspec integration test 
that tests for it</p>




<h2 id="fix">Fix the problems</h2>

<p>For every weakness you find: fix it.</p>
<p>If you wrote your hacks as rspec test, those test should
be succeeding now.</p>

app/views/static_pages/home.html.erb
<h1>HackMe</h1>
<p>A simple blogging App for many users who want to blog together.
<br><i>in reality: just a sample app to learn about security in rails </i></p>


<% @articles.each do |article| %>
  <h2><%= article.title %></h2>
  <%= raw article.description %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :homepage %><br />
    <%= f.text_field :homepage %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>

  <% if current_user and current_user.admin? %>
  <div class="field">
    <%= f.label :is_admin %><br />
    <%= f.check_box :is_admin %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>People</h1>

<% if current_user and current_user.admin? then %>
  <%= link_to 'New User', new_user_path %>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Homepage</th>
    <th>Password</th>
    <th>Admin</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_unless_blank("Homepage", user.homepage) %></td>
    <td><%= user.password %></td>
    <td><%= user.admin? %></td>
    <% if current_user and ( current_user.admin? or user.id == current_user.id ) then %>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
<p>
  <b>Homepage:</b>
  <%= link_unless_blank("Homepage", @user.homepage) %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <% if @user.admin? %>
    <b>Admin</b>
  <% else %>
    Nicht Admin
  <% end %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>